default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: myapp_user
  password: myapp_password
  host: localhost

development:
  <<: *default
  database: school_api_development

test:
  <<: *default
  database: school_api_test

production:
  <<: *default
  database: school_api_production
  username: school_api
  password: <%= ENV['SCHOOL_API_DATABASE_PASSWORD'] %>